package com.example.catalinadinu.eventive.Clase;

public enum Categorii {
    LOCATIE, CATERING, DECORATIUNI, MUZICA, FOTO_VIDEO, PERSONAL, CEREMONII_RELIGIOASE, ARANJAMENTE_FLORALE,
    PAPETARIE, ANIMATIE_DIVERTISMENT, MARTURII, ALTELE
}
