package com.example.catalinadinu.eventive.Clase;

public class Const {
    public static final String CHEIE_TRIMITERE_TIP_UTILIZATOR_LOGIN_DASH = "CHEIE_TRIMITERE_TIP_UTILIZATOR_LOGIN_DASH";
    public static final String CHEIE_TRIMITERE_TIP_UTILIZATOR_DASH_LISTA_SERVICII = "CHEIE_TRIMITERE_TIP_UTILIZATOR_DASH_LISTA_SERVICII";
    public static final String CHEIE_TRIMITERE_CATEGORIE_DASH_LISTA = "CHEIE_TRIMITERE_CATEGORIE_DASH_LISTA";
    public static final String CHEIE_TRIMITERE_SERVICIU_VIZUALIZARE = "CHEIE_TRIMITERE_SERVICIU_VIZUALIZARE";
    public static final String CHEIE_TRIMITERE_DENUMIRE_FURNIZOR_DETALII = "CHEIE_TRIMITERE_DENUMIRE_FURNIZOR_DETALII";
    public static final String CHEIE_TRMIITERE_FLAG_SERVICII_FILTRATE = "CHEIE_TRMIITERE_FLAG_SERVICII_FILTRATE";
    public static final String CHEIE_TRIMITERE_FLAG_MODIFICARE_SERVICIU = "CHEIE_TRIMITERE_FLAG_MODIFICARE_SERVICIU";
    public static final String CHEIE_TRIMITERE_SERVICIU_DE_MODIFICAT = "CHEIE_TRIMITERE_SERVICIU_DE_MODIFICAT";
    public static final String CHEIE_TRIMITERE_TIP_UTILIZATOR_VIZ_SERV = "CHEIE_TRIMITERE_TIP_UTILIZATOR_VIZ_SERV";
    public static final String CHEIE_TRIMITERE_VIZUALIZARE_REZERVARE_FURNIZOR = "CHEIE_TRIMITERE_VIZUALIZARE_REZERVARE_FURNIZOR";
    public static final String CHEIE_TRIMITERE_VIZUALIZARE_REZERVARE = "CHEIE_TRIMITERE_VIZUALIZARE_REZERVARE";

    public static final String EDITARE = "editare";
}
