package com.example.catalinadinu.eventive.Clase;

public class Const {
    public static final String CHEIE_TRIMITERE_TIP_UTILIZATOR_LOGIN_DASH = "CHEIE_TRIMITERE_TIP_UTILIZATOR_LOGIN_DASH";
    public static final String CHEIE_TRIMITERE_TIP_UTILIZATOR_DASH_LISTA_SERVICII = "CHEIE_TRIMITERE_TIP_UTILIZATOR_DASH_LISTA_SERVICII";
    public static final String CHEIE_TRIMITERE_CATEGORIE_DASH_LISTA = "CHEIE_TRIMITERE_CATEGORIE_DASH_LISTA";
}
